// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210719193119_PostgresInitial")]
    partial class PostgresInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("API.Entities.Rates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("AED")
                        .HasColumnType("double precision");

                    b.Property<double>("AFN")
                        .HasColumnType("double precision");

                    b.Property<double>("ALL")
                        .HasColumnType("double precision");

                    b.Property<double>("AMD")
                        .HasColumnType("double precision");

                    b.Property<double>("ANG")
                        .HasColumnType("double precision");

                    b.Property<double>("AOA")
                        .HasColumnType("double precision");

                    b.Property<double>("ARS")
                        .HasColumnType("double precision");

                    b.Property<double>("AUD")
                        .HasColumnType("double precision");

                    b.Property<double>("AWG")
                        .HasColumnType("double precision");

                    b.Property<double>("AZN")
                        .HasColumnType("double precision");

                    b.Property<double>("BAM")
                        .HasColumnType("double precision");

                    b.Property<double>("BBD")
                        .HasColumnType("double precision");

                    b.Property<double>("BDT")
                        .HasColumnType("double precision");

                    b.Property<double>("BGN")
                        .HasColumnType("double precision");

                    b.Property<double>("BHD")
                        .HasColumnType("double precision");

                    b.Property<double>("BIF")
                        .HasColumnType("double precision");

                    b.Property<double>("BMD")
                        .HasColumnType("double precision");

                    b.Property<double>("BND")
                        .HasColumnType("double precision");

                    b.Property<double>("BOB")
                        .HasColumnType("double precision");

                    b.Property<double>("BRL")
                        .HasColumnType("double precision");

                    b.Property<double>("BSD")
                        .HasColumnType("double precision");

                    b.Property<double>("BTC")
                        .HasColumnType("double precision");

                    b.Property<double>("BTN")
                        .HasColumnType("double precision");

                    b.Property<double>("BWP")
                        .HasColumnType("double precision");

                    b.Property<double>("BYN")
                        .HasColumnType("double precision");

                    b.Property<double>("BZD")
                        .HasColumnType("double precision");

                    b.Property<double>("CAD")
                        .HasColumnType("double precision");

                    b.Property<double>("CDF")
                        .HasColumnType("double precision");

                    b.Property<double>("CHF")
                        .HasColumnType("double precision");

                    b.Property<double>("CLF")
                        .HasColumnType("double precision");

                    b.Property<double>("CLP")
                        .HasColumnType("double precision");

                    b.Property<double>("CNH")
                        .HasColumnType("double precision");

                    b.Property<double>("CNY")
                        .HasColumnType("double precision");

                    b.Property<double>("COP")
                        .HasColumnType("double precision");

                    b.Property<double>("CRC")
                        .HasColumnType("double precision");

                    b.Property<double>("CUC")
                        .HasColumnType("double precision");

                    b.Property<double>("CUP")
                        .HasColumnType("double precision");

                    b.Property<double>("CVE")
                        .HasColumnType("double precision");

                    b.Property<double>("CZK")
                        .HasColumnType("double precision");

                    b.Property<double>("DJF")
                        .HasColumnType("double precision");

                    b.Property<double>("DKK")
                        .HasColumnType("double precision");

                    b.Property<double>("DOP")
                        .HasColumnType("double precision");

                    b.Property<double>("DZD")
                        .HasColumnType("double precision");

                    b.Property<double>("EGP")
                        .HasColumnType("double precision");

                    b.Property<double>("ERN")
                        .HasColumnType("double precision");

                    b.Property<double>("ETB")
                        .HasColumnType("double precision");

                    b.Property<double>("EUR")
                        .HasColumnType("double precision");

                    b.Property<double>("FJD")
                        .HasColumnType("double precision");

                    b.Property<double>("FKP")
                        .HasColumnType("double precision");

                    b.Property<double>("GBP")
                        .HasColumnType("double precision");

                    b.Property<double>("GEL")
                        .HasColumnType("double precision");

                    b.Property<double>("GGP")
                        .HasColumnType("double precision");

                    b.Property<double>("GHS")
                        .HasColumnType("double precision");

                    b.Property<double>("GIP")
                        .HasColumnType("double precision");

                    b.Property<double>("GMD")
                        .HasColumnType("double precision");

                    b.Property<double>("GNF")
                        .HasColumnType("double precision");

                    b.Property<double>("GTQ")
                        .HasColumnType("double precision");

                    b.Property<double>("GYD")
                        .HasColumnType("double precision");

                    b.Property<double>("HKD")
                        .HasColumnType("double precision");

                    b.Property<double>("HNL")
                        .HasColumnType("double precision");

                    b.Property<double>("HRK")
                        .HasColumnType("double precision");

                    b.Property<double>("HTG")
                        .HasColumnType("double precision");

                    b.Property<double>("HUF")
                        .HasColumnType("double precision");

                    b.Property<double>("IDR")
                        .HasColumnType("double precision");

                    b.Property<double>("ILS")
                        .HasColumnType("double precision");

                    b.Property<double>("IMP")
                        .HasColumnType("double precision");

                    b.Property<double>("INR")
                        .HasColumnType("double precision");

                    b.Property<double>("IQD")
                        .HasColumnType("double precision");

                    b.Property<double>("IRR")
                        .HasColumnType("double precision");

                    b.Property<double>("ISK")
                        .HasColumnType("double precision");

                    b.Property<double>("JEP")
                        .HasColumnType("double precision");

                    b.Property<double>("JMD")
                        .HasColumnType("double precision");

                    b.Property<double>("JOD")
                        .HasColumnType("double precision");

                    b.Property<double>("JPY")
                        .HasColumnType("double precision");

                    b.Property<double>("KES")
                        .HasColumnType("double precision");

                    b.Property<double>("KGS")
                        .HasColumnType("double precision");

                    b.Property<double>("KHR")
                        .HasColumnType("double precision");

                    b.Property<double>("KMF")
                        .HasColumnType("double precision");

                    b.Property<double>("KPW")
                        .HasColumnType("double precision");

                    b.Property<double>("KRW")
                        .HasColumnType("double precision");

                    b.Property<double>("KWD")
                        .HasColumnType("double precision");

                    b.Property<double>("KYD")
                        .HasColumnType("double precision");

                    b.Property<double>("KZT")
                        .HasColumnType("double precision");

                    b.Property<double>("LAK")
                        .HasColumnType("double precision");

                    b.Property<double>("LBP")
                        .HasColumnType("double precision");

                    b.Property<double>("LKR")
                        .HasColumnType("double precision");

                    b.Property<double>("LRD")
                        .HasColumnType("double precision");

                    b.Property<double>("LSL")
                        .HasColumnType("double precision");

                    b.Property<double>("LYD")
                        .HasColumnType("double precision");

                    b.Property<double>("MAD")
                        .HasColumnType("double precision");

                    b.Property<double>("MDL")
                        .HasColumnType("double precision");

                    b.Property<double>("MGA")
                        .HasColumnType("double precision");

                    b.Property<double>("MKD")
                        .HasColumnType("double precision");

                    b.Property<double>("MMK")
                        .HasColumnType("double precision");

                    b.Property<double>("MNT")
                        .HasColumnType("double precision");

                    b.Property<double>("MOP")
                        .HasColumnType("double precision");

                    b.Property<double>("MRO")
                        .HasColumnType("double precision");

                    b.Property<double>("MRU")
                        .HasColumnType("double precision");

                    b.Property<double>("MUR")
                        .HasColumnType("double precision");

                    b.Property<double>("MVR")
                        .HasColumnType("double precision");

                    b.Property<double>("MWK")
                        .HasColumnType("double precision");

                    b.Property<double>("MXN")
                        .HasColumnType("double precision");

                    b.Property<double>("MYR")
                        .HasColumnType("double precision");

                    b.Property<double>("MZN")
                        .HasColumnType("double precision");

                    b.Property<double>("NAD")
                        .HasColumnType("double precision");

                    b.Property<double>("NGN")
                        .HasColumnType("double precision");

                    b.Property<double>("NIO")
                        .HasColumnType("double precision");

                    b.Property<double>("NOK")
                        .HasColumnType("double precision");

                    b.Property<double>("NPR")
                        .HasColumnType("double precision");

                    b.Property<double>("NZD")
                        .HasColumnType("double precision");

                    b.Property<double>("OMR")
                        .HasColumnType("double precision");

                    b.Property<double>("PAB")
                        .HasColumnType("double precision");

                    b.Property<double>("PEN")
                        .HasColumnType("double precision");

                    b.Property<double>("PGK")
                        .HasColumnType("double precision");

                    b.Property<double>("PHP")
                        .HasColumnType("double precision");

                    b.Property<double>("PKR")
                        .HasColumnType("double precision");

                    b.Property<double>("PLN")
                        .HasColumnType("double precision");

                    b.Property<double>("PYG")
                        .HasColumnType("double precision");

                    b.Property<double>("QAR")
                        .HasColumnType("double precision");

                    b.Property<double>("RON")
                        .HasColumnType("double precision");

                    b.Property<double>("RSD")
                        .HasColumnType("double precision");

                    b.Property<double>("RUB")
                        .HasColumnType("double precision");

                    b.Property<double>("RWF")
                        .HasColumnType("double precision");

                    b.Property<double>("SAR")
                        .HasColumnType("double precision");

                    b.Property<double>("SBD")
                        .HasColumnType("double precision");

                    b.Property<double>("SCR")
                        .HasColumnType("double precision");

                    b.Property<double>("SDG")
                        .HasColumnType("double precision");

                    b.Property<double>("SEK")
                        .HasColumnType("double precision");

                    b.Property<double>("SGD")
                        .HasColumnType("double precision");

                    b.Property<double>("SHP")
                        .HasColumnType("double precision");

                    b.Property<double>("SLL")
                        .HasColumnType("double precision");

                    b.Property<double>("SOS")
                        .HasColumnType("double precision");

                    b.Property<double>("SRD")
                        .HasColumnType("double precision");

                    b.Property<double>("SSP")
                        .HasColumnType("double precision");

                    b.Property<double>("STD")
                        .HasColumnType("double precision");

                    b.Property<double>("STN")
                        .HasColumnType("double precision");

                    b.Property<double>("SVC")
                        .HasColumnType("double precision");

                    b.Property<double>("SYP")
                        .HasColumnType("double precision");

                    b.Property<double>("SZL")
                        .HasColumnType("double precision");

                    b.Property<double>("THB")
                        .HasColumnType("double precision");

                    b.Property<double>("TJS")
                        .HasColumnType("double precision");

                    b.Property<double>("TMT")
                        .HasColumnType("double precision");

                    b.Property<double>("TND")
                        .HasColumnType("double precision");

                    b.Property<double>("TOP")
                        .HasColumnType("double precision");

                    b.Property<double>("TRY")
                        .HasColumnType("double precision");

                    b.Property<double>("TTD")
                        .HasColumnType("double precision");

                    b.Property<double>("TWD")
                        .HasColumnType("double precision");

                    b.Property<double>("TZS")
                        .HasColumnType("double precision");

                    b.Property<double>("UAH")
                        .HasColumnType("double precision");

                    b.Property<double>("UGX")
                        .HasColumnType("double precision");

                    b.Property<double>("USD")
                        .HasColumnType("double precision");

                    b.Property<double>("UYU")
                        .HasColumnType("double precision");

                    b.Property<double>("UZS")
                        .HasColumnType("double precision");

                    b.Property<double>("VES")
                        .HasColumnType("double precision");

                    b.Property<double>("VND")
                        .HasColumnType("double precision");

                    b.Property<double>("VUV")
                        .HasColumnType("double precision");

                    b.Property<double>("WST")
                        .HasColumnType("double precision");

                    b.Property<double>("XAF")
                        .HasColumnType("double precision");

                    b.Property<double>("XAG")
                        .HasColumnType("double precision");

                    b.Property<double>("XAU")
                        .HasColumnType("double precision");

                    b.Property<double>("XCD")
                        .HasColumnType("double precision");

                    b.Property<double>("XDR")
                        .HasColumnType("double precision");

                    b.Property<double>("XOF")
                        .HasColumnType("double precision");

                    b.Property<double>("XPD")
                        .HasColumnType("double precision");

                    b.Property<double>("XPF")
                        .HasColumnType("double precision");

                    b.Property<double>("XPT")
                        .HasColumnType("double precision");

                    b.Property<double>("YER")
                        .HasColumnType("double precision");

                    b.Property<double>("ZAR")
                        .HasColumnType("double precision");

                    b.Property<double>("ZMW")
                        .HasColumnType("double precision");

                    b.Property<double>("ZWL")
                        .HasColumnType("double precision");

                    b.Property<double>("timestamp")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
